### ISSUE TITLE
rails_refactor gem rename my model name but not it's class name.

### ISSUE THREAD

**Issue by Gags007** [jcrisp/rails_refactor#8]
Hi, I am new bee to ROR. I was looking to rename my model & controller name and come to this gem. As per instruction I have installed this gem and also tried to rename my model by this way
rails_refactor rename OldModelName NewModelName
It successfully change the model name but not its class name and all reference objects. Any idea or suggestion.. Thanks in advance

**Comment by jcrisp** [comment]
Please let me know if you're still interested / having the issue and I'll take a look.
Cheers
James
